### PR TITLE
Add Sources field to Config

### PR DESCRIPTION
**Pull request by jimmykarily**
and keep track of merged files there. Also print the Sources as a comment in the String() method.

Part of https://github.com/kairos-io/kairos/issues/2737

(not really documentation but need this to make the docs clearer)

Allows us to generate something like this:

```
#cloud-config

# Sources:
# - /oem/90_custom.yaml
# - https://gist.githubusercontent.com/jimmykarily/1929503dc95accfe46aaeff51b189610/raw/a7c9c1226c7c677d85d6471dffd0f2075183a6fd/gistfile1.txt
# - https://gist.githubusercontent.com/jimmykarily/ffe85c12e81dda5fde16657065989709/raw/4c60a385a7f390e10b9be51ee124756d896399e2/gistfile1.txt

config_url: https://gist.githubusercontent.com/jimmykarily/ffe85c12e81dda5fde16657065989709/raw/4c60a385a7f390e10b9be51ee124756d896399e2/gistfile1.txt
debug: true
install:
    poweroff: false
    reboot: false
k3s:
    enabled: true
users:
    - name: kairos
      passwd: kairos
```

### CODE REVIEW

**Comment by jimmykarily** [comment]
TODO: Need to add sources to the configs coming from remote urls, cmdline etc

**Comment by jimmykarily** [comment]
I'm opening this for review to gather the team's feedback. There are a couple of TODOs but we can worry about them only if we decide we want this change.

**Comment by anthonyra** [comment]
> The `kairos-agent config` command will produce reliable results only on an installed system because no configuration options come from the command line and such (e.g. by using `--debug`). At that point, installation is already done, so the only reason to use the command would be to see the reset and upgrade configuration and any user defined stages (because the system ones are skipped due to [the removal of that path](https://github.com/kairos-io/kairos-agent/pull/550/files#diff-36043890c52c8201a8bc84238c219be45ce07bf172d89f693c7c54ffe70d046eL174) and the lack of `#cloud-config` header).

I actually just posted in slack a question related to this - we are building a custom OS with Kairos as base. We are wanting to lock it down a little more. As such, being able to see what config was used during the installation process is going to be huge for us to ensure we built it as intended and know what is active or not.

Specifically we intend to run a more strict version of <https://github.com/kairos-io/packages/blob/a1ee7d4fa956e4b764891f299e85ee82f5d576ac/packages/static/kairos-overlay-files/files/system/oem/50_recovery.yaml#L21>

To clarify, will the system ones still be active? I originally read this as the system ones would be skipped but is it just being skipped from the `kairos-agent config` standpoint but are still ran on install?

**Comment by jimmykarily** [comment]
> > The `kairos-agent config` command will produce reliable results only on an installed system because no configuration options come from the command line and such (e.g. by using `--debug`). At that point, installation is already done, so the only reason to use the command would be to see the reset and upgrade configuration and any user defined stages (because the system ones are skipped due to [the removal of that path](https://github.com/kairos-io/kairos-agent/pull/550/files#diff-36043890c52c8201a8bc84238c219be45ce07bf172d89f693c7c54ffe70d046eL174) and the lack of `#cloud-config` header).
> 
> I actually just posted in slack a question related to this - we are building a custom OS with Kairos as base. We are wanting to lock it down a little more. As such, being able to see what config was used during the installation process is going to be huge for us to ensure we built it as intended and know what is active or not.
> 
> Specifically we intend to run a more strict version of https://github.com/kairos-io/packages/blob/a1ee7d4fa956e4b764891f299e85ee82f5d576ac/packages/static/kairos-overlay-files/files/system/oem/50_recovery.yaml#L21
> 
> To clarify, will the system ones still be active? I originally read this as the system ones would be skipped but is it just being skipped from the `kairos-agent config` standpoint but are still ran on install?

The system ones ([these](https://github.com/kairos-io/packages/tree/main/packages/static/kairos-overlay-files/files/system/oem)) don't define any `install:` or `reset:` or `upgrade:` options. They only define "stages" which are taken into account by kairos (`immucore` binary) during boot.

That's the reason we decided they are not relevant to the `kairos-agent config` command and that's the reason they didn't have a `#cloud-config` header (thus they were skipped). To make it even more clear that there is no option there that is relevant to the installation, we decided that we should better [completely remove](https://github.com/kairos-io/kairos-agent/pull/550/files#diff-36043890c52c8201a8bc84238c219be45ce07bf172d89f693c7c54ffe70d046eL174) that directory from those scanned by the kairos-agent.

What do you mean by "more strict version"? Can you explain the use case in a bit more detail?

**Comment by anthonyra** [comment]
Ahh okay I'm tracking with what is meant there.

> What do you mean by "more strict version"? Can you explain the use case in a bit more detail?

For our use case, we don't want our users to be able to boot the device into recovery mode and have access to do things. I know that the OS is immutable and there's only so much they could do on the installed version (if anything). We just don't want them to even poke around aimlessly. We'd like to instead only offer them a kiosk mode to do such things.

**Comment by jimmykarily** [comment]
> Ahh okay I'm tracking with what is meant there.
> 
> > What do you mean by "more strict version"? Can you explain the use case in a bit more detail?
> 
> For our use case, we don't want our users to be able to boot the device into recovery mode and have access to do things. I know that the OS is immutable and there's only so much they could do on the installed version (if anything). We just don't want them to even poke around aimlessly. We'd like to instead only offer them a kiosk mode to do such things.

That's indeed very nice idea. We already [create and admin group](https://github.com/kairos-io/packages/blob/a1ee7d4fa956e4b764891f299e85ee82f5d576ac/packages/static/kairos-overlay-files/files/system/oem/10_accounting.yaml#L6) which is for users with `sudo` permissions. I wonder we should only allow users of that group to login (locally or with ssh), using PAM.

**Comment by jimmykarily** [comment]
Installing with this config prevents all logins in recovery:

```
#cloud-config

install:
    poweroff: false
    reboot: false
stages:
    initramfs:
        - commands:
            - echo "Logins are disabled." > /etc/nologin
          if: '[ -f "/run/cos/recovery_mode" ]'
          name: Prevent logins on recovery
users:
    - name: kairos
      passwd: kairos
    - name: dimitris
      passwd: kairos
```

If you play around with PAM you may be able to limit logins to just admins (e.g. [like described here](https://www.cyberciti.biz/tips/howto-deny-allow-linux-user-group-login.html)).

**Review by mauromorales — COMMENTED** [review]
Overall, I really like the idea 👏 

If I get it right, it will put each source according to how it merged it, so if one would manually follow the process, I could tell why a certain value was overwritten. With 2 files that would work, but with 10+ I guess it would be very hard.

I wonder if what we need long term is more of a "ledger" lacking a better name. And that I could quickly ask the config, where does this value come from, and points me to the source that brought it in ... or comment the full yaml with sources?

```
#cloud-config
key_one:
  sub_key_one: value2 #source ./file/path.extension
```

wdyt?

**Comment by jimmykarily** [comment]
@mauromorales what you describe would be even better. The problem is that comments are lost when yamls are unmarshalled to objects and the configs spend most of their time in code being objects. If we need full tracking of where the values are coming from, we need to completely change how we merged yamls and such.

**Comment by mauromorales** [comment]
@jimmykarily yup you're right. I'd really like for us to have a smarter marshalling 🤣  Because I find it so strange that you can have a single cloud-config file that you feed the system, and when you check the resulting file, it doesn't follow the same order that you put it in. But maybe that's just a nice to have for now in comparison to other features in the backlog

**Review by mauromorales — APPROVED** [review]

**Pull request merged**
