### PR TITLE
Common logger for Kairos libs

### PR DESCRIPTION
**Pull request by Itxaka**
This implements a middle interface in order to have our logger, based on zerolog, but still be able to plug it in in places where zerolog may not be used like yip.

This gives us access to a generic logger similar to logrus for the agent+yip while exposing the internal zerolog for things like immucore.

That way we dont have to move into changing the full logger in the agent and can still use it in yip, while moving to use zerolog underneath for the agent.

Part of: https://github.com/kairos-io/kairos/issues/1188

### CODE REVIEW

**Comment by Itxaka** [comment]
This provides a simple interface for simple logging like logrus does:

```
KairosLog.Info("Hello")
KairosLog.Infof("Hello %s", name)
```

Also the full zerlog implementation under `KairosLog.Logger` for more complex and structured logging:

```
KairosLog.Logger.Info().Str("commit", v.GitCommit).Str("compiled with", v.GoVersion).Str("version", v.Version).Msg("Immucore")
KairosLog.Logger.Debug().Interface("mounts", s.CustomMounts).Msg("Mounting custom mounts")
```

**Comment by Itxaka** [comment]
This is the output from calling Info directly:

```
<nil> INF BOOT_IMAGE=(hd1,gpt5)/vmlinuz-6.4.7-200.fc38.x86_64 root=UUID=28325140-fd92-4d87-94d5-eedb896ee632 ro rootflags=subvol=root initcall_blacklist=simpledrm_platform_driver_init rhgb quiet initcall_blacklist=simpledrm_platform_driver_init rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1
```

And this the one from calling Logger.Info:

```
<nil> INF cmdline content="BOOT_IMAGE=(hd1,gpt5)/vmlinuz-6.4.7-200.fc38.x86_64 root=UUID=28325140-fd92-4d87-94d5-eedb896ee632 ro rootflags=subvol=root initcall_blacklist=simpledrm_platform_driver_init rhgb quiet initcall_blacklist=simpledrm_platform_driver_init rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1\n"
```

**Review by mauromorales — APPROVED** [review]
lgtm

**Comment by Itxaka** [comment]
nah, dont really liking it, dropping it so somebody can pick this up and come up with a better solution. Maybe the solution is to just use zerolog everywhere in the agent and call it a day, passing a bridge logger to yip.

**Pull request closed without merging**
